### ISSUE TITLE
examplemod.java

### ISSUE THREAD

**Issue by The-Forecaster** [Officer32k/autohak#1]
lol

**Comment by Officer32k** [comment]
don't ask me what i made her it's terrible i was retarded this litterally has nothing and idk why i made it LMAO

**Comment by Officer32k** [comment]
wait

**Comment by Officer32k** [comment]
what the fuck i made actual modules ????????

**Comment by Officer32k** [comment]
i didn't even fucking know java at that time what?
this is fukcing weiiiiiiiiiiiird
